---
title: "Multiples of 3 and 5"
author: "EKU R User Group"
date: "25 February 2020"
output: html_document
---

## Project Euler

> Project Euler is a series of challenging mathematical/computer programming problems that will require more than just mathematical insights to solve. (https://projecteuler.net/about)

For this month's challenge, we will use some of the elements of last month's challenge to complete the first two problems in Project Euler.

### Project Euler - Problem 1

> If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.
> 
> Find the sum of all the multiples of 3 or 5 below 1000.

### Project Euler - Problem 2

>Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
> 
> 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
> 
> By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

## Hint 

* For problem 2, you may consider using a `while` loop.  For example, the following generates the first ten values of the Fibonacchi series:

```{r}
fib <- 1:2
i <- 3

while(i <= 10){
  fib[i] <- fib[i - 2] + fib[i - 1]
  i <- i + 1
}

fib
```

* `while` will continue looping as long as the evaluation in `while( condition )` resolves to true.  In the previous example, when `i` became 11, the loop stopped running.
* The condition need not be based on the iterator `i`.  It could, for example, be based on the maximum value in `fib`.